version: "3.3"

networks:
  backend:

services:

  jupyter:
    image: jupyter/pyspark-notebook:29edefbcb06a # The image contains Spark 3.0.2 and Python 3.8.8
    command: /usr/local/bin/start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' # Empty password and token
    networks:
      - backend
    ports:
      - 8888:8888 # Expose Jupyter Notebook GUI
    volumes:
      - ./jupyter:/home/jovyan

  cassandra:
    image: cassandra:3.11
    environment:
      - HEAP_NEWSIZE=2G
      - MAX_HEAP_SIZE=4G
      - CASSANDRA_CLUSTER_NAME=jupyter
    networks:
      - backend

  spark-master:
    image: custom-bitnami-spark # Custom build image with Spark 3.0.2 and Python 3.8.8 from bitnami-spark base
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8080:8080 # Master dashboard
      - 7077:7077
    networks:
      - backend
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf # Make sure to include DataStax Spark Cassandra Connector
      - ./spark/jars_dir:/opt/bitnami/spark/jars/ivy:z
      - ./jupyter/data:/home/jovyan/data # Share data directory (for Vermont notebook)

  spark-worker-1:
    image: custom-bitnami-spark # Custom build image with Spark 3.0.2 and Python 3.8.8 from bitnami-spark base
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8081:8081 # Worker dashboard #1
    networks:
      - backend
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf # Make sure to include DataStax Spark Cassandra Connector
      - ./spark/jars_dir:/opt/bitnami/spark/jars/ivy:z
      - ./jupyter/data:/home/jovyan/data # Share data directory (for Vermont notebook)

  spark-worker-2:
    image: custom-bitnami-spark # Custom build image with Spark 3.0.2 and Python 3.8.8 from bitnami-spark base
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8082:8081 # Worker dashboard #2
    networks:
      - backend
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf # Make sure to include DataStax Spark Cassandra Connector
      - ./spark/jars_dir:/opt/bitnami/spark/jars/ivy:z
      - ./jupyter/data:/home/jovyan/data # Share data directory (for Vermont notebook)